- lib/sets-builder/index.js
- lib/sets-builder/test-set.js
- test/sets-builder/index.js
- test/sets-builder/test-set.js
На данный момент, если через cli в gemini или hermione прилетят абсолютные пути, то тесты не запустятся. 
Пофиксил эту проблему здесь.
> resolve files specified to use

- package.json
> chore: move istanbul to dev dependencies

- README.md
- index.js
- lib/browser-pool/basic-pool.js
- lib/browser-pool/caching-pool.js
- lib/browser-pool/index.js
- lib/browser-pool/limited-pool.js
- lib/browser-pool/limited-use-set.js
- lib/browser-pool/per-browser-limited-pool.js
- lib/browser-pool/pool.js
- lib/errors/cancelled-error.js
- lib/errors/index.js
- package.json
- test/browser-pool/basic-pool.js
- test/browser-pool/caching-pool.js
- test/browser-pool/index.js
- test/browser-pool/limited-pool.js
- test/browser-pool/per-browser-limited-pool.js
- test/browser-pool/util.js
- test/setup.js
Copied from gemini with some modifications: entry points added
> Browser Pool

- README.md
- index.js
- lib/browser-agent/index.js
- test/browser-agent/index.js
cc @j0tunn 
Буквально копипаста из gemini, так как в hermione будет такой же код с точностью до пробела :)
> Browser Agent

- lib/sets-builder/test-set.js
- test/sets-builder/test-set.js
> fix: do not mutate original config in 'SetsBuilder'

- README.md
- index.js
- lib/image/index.js
- lib/image/safe-rect.js
- lib/temp/index.js
- lib/utils.js
- package-lock.json
- package.json
- test/image/index.js
- test/image/safe-rect.js
- test/temp/index.js
> Add Image and Temp

- lib/promise-utils/index.js
- package-lock.json
- package.json
Native method 'find' should now not be changed
> Use glob-extra 3.0.0, get rid of q and q-io dependencies

- lib/calibrator/index.js
related to https://github.com/gemini-testing/hermione/pull/218
> fix: browser calibration

- .gitignore
- README.md
- index.js
- lib/browser/client-scripts/index.coverage.js
- lib/browser/client-scripts/index.js
- lib/browser/client-scripts/lib.compat.js
- lib/browser/client-scripts/lib.native.js
- lib/browser/client-scripts/polyfills/LICENSE.md
- lib/browser/client-scripts/polyfills/getComputedStyle.js
- lib/browser/client-scripts/polyfills/matchMedia.js
- lib/browser/client-scripts/rect.js
- lib/browser/client-scripts/util.js
- lib/client-bridge/client-bridge.js
- lib/client-bridge/index.js
- lib/coord-validator/index.js
- lib/coverage/coverage-level.js
- lib/errors/client-bridge-error.js
- lib/errors/height-viewport-error.js
- lib/errors/index.js
- lib/errors/offset-viewport-error.js
- package-lock.json
- package.json
- test/lib/browser/client-scripts/rect.js
- test/lib/client-bridge/client-bridge.js
- test/lib/client-bridge/index.js
- test/lib/coord-validator/index.js
- test/lib/coverage/coverage-level.js
cc @j0tunn @sipayRT @rostik404 @DudaGod 
Пока без тестов и какой-либо документации.
Тут по факту нужно поревьюить только файл:
```
lib/client-bridge/index.js
```
> feat(hermione): assert view by selectors

- lib/browser/client-scripts/ignore-areas.deprecated.js
- lib/browser/client-scripts/ignore-areas.js
- lib/browser/client-scripts/index.js
- lib/client-bridge/index.js
- lib/screen-shooter/index.js
- test/lib/client-bridge/index.js
- test/lib/screen-shooter/index.js
@j0tunn @sipayRT @DudaGod 
Тесты будут позже.
> feat: add feature 'ignoreElements' to 'ScreenShooter'

- .travis.yml
- package.json
Node 6 doesnt have implementations for async functions, but they exists in this repo tests.
For example in my other PR I got:
https://travis-ci.org/gemini-testing/gemini-core/jobs/463509076
```
/home/travis/build/gemini-testing/gemini-core/test/lib/browser-agent/index.js:29
it('should request browser with passed options', async () => {
^
SyntaxError: Unexpected token (
at createScript (vm.js:56:10)
```
> Requires NodeJs > 8

- lib/image/index.js
- package-lock.json
- package.json
- test/lib/image/index.js
TODO: не забыть обновить версию looks-same
> feat: pass stopOnFirstFail option to looksame

- lib/base-stats/index.js
Done for https://github.com/gemini-testing/hermione/pull/370
> refactor: extract more methods for the sake of derived classes

- lib/screen-shooter/index.js
- test/lib/screen-shooter/index.js
https://github.com/gemini-testing/hermione/pull/394
https://nda.ya.ru/3UYieV
> Add screenshotDelay option for screenShooter

- package-lock.json
- package.json
Fixes #54 
Changelog: [v3](https://github.com/micromatch/micromatch/blob/master/CHANGELOG.md#300---2017-04-11), [v4](https://github.com/micromatch/micromatch/blob/master/CHANGELOG.md#breaking-changes)
> Update micromatch to v4

- package-lock.json
- package.json
Required for fixing https://github.com/gemini-testing/hermione/issues/456 https://github.com/gemini-testing/hermione/issues/359
> Update packages to fix vulnerabilities reported by npm audit

- package-lock.json
- package.json
BREAKING_CHANGES: some glob options in "SetsBuilder.build" method are changed. More info here - https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0
> feat: update glob-extra@5.0.0

- lib/browser-pool/index.js
- lib/browser-pool/limited-pool.js
- test/lib/browser-pool/limited-pool.js
More info here - https://nda.ya.ru/t/mfBpCbeG3XruUp
> fix: incorrect free browser in limited pool for all browsers

- package-lock.json
- package.json
https://github.com/gemini-testing/png-img/pull/62
> fix: update png-img version to support arm bindings

- lib/browser/client-scripts/index.js
- lib/browser/client-scripts/rect.js
- test/lib/browser/client-scripts/rect.js
Что сделано:
* добавил в метод подготовки к скриншоту возможность передать опцию, определяющую снимаемую область. При наличии этой области переданные селекторы не используются
> feat: allow to screenshoot custom area
